# Generated by Django 6.1.1 on 2026-09-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
    ]
