# Generated by Django 6.1.1 on 2026-09-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_remove_profile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_address',
        ),
    ]
